"""
services/transcript.py
MIDI → human-readable note transcript using pretty_midi.
"""

from pathlib import Path
import pretty_midi

NOTE_NAMES = ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B']


def _note_name(midi_num: int) -> str:
    octave = (midi_num // 12) - 1
    return f"{NOTE_NAMES[midi_num % 12]}{octave}"


def generate_transcript(midi_path: str, output_txt: str, tempo: int = 120) -> None:
    """
    Parse a MIDI file and write a readable note transcript.

    Output columns:
        NOTE   VEL   START     END       DURATION
        C4     87    0.000s    0.450s    0.450s
    """
    if not Path(midi_path).exists():
        raise FileNotFoundError(f"MIDI not found: {midi_path}")

    pm = pretty_midi.PrettyMIDI(midi_path)

    lines = [
        "╔══════════════════════════════════════════════════════╗",
        "║         SoundForge AI — Note Transcript              ║",
        "╚══════════════════════════════════════════════════════╝",
        "",
        f"  Tempo          : {tempo} BPM",
        f"  Total duration : {pm.get_end_time():.2f} seconds",
        f"  Instruments    : {len(pm.instruments)}",
        f"  Total notes    : {sum(len(i.notes) for i in pm.instruments)}",
        "",
        "──────────────────────────────────────────────────────",
        f"  {'NOTE':<6} {'VEL':>4}  {'START':>8}  {'END':>8}  {'DURATION':>8}",
        "──────────────────────────────────────────────────────",
    ]

    for instrument in pm.instruments:
        instr_label = pretty_midi.program_to_instrument_name(instrument.program)
        drum_label  = " [DRUMS]" if instrument.is_drum else ""
        lines.append(f"\n  ▸ Track: {instr_label}{drum_label}")
        lines.append(f"  {'─'*50}")

        for note in sorted(instrument.notes, key=lambda n: n.start):
            name = _note_name(note.pitch)
            dur  = note.end - note.start
            lines.append(
                f"  {name:<6} {note.velocity:>4}  "
                f"{note.start:>7.3f}s  {note.end:>7.3f}s  {dur:>7.3f}s"
            )

    lines += [
        "",
        "──────────────────────────────────────────────────────",
        "  Generated by SoundForge AI — soundforgeai.com",
        "──────────────────────────────────────────────────────",
    ]

    Path(output_txt).write_text("\n".join(lines), encoding="utf-8")


